version: "3.7"
services:
  db:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 1Secure*Password1
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Enterprise"
    ports:
      - "1433:1433"
  seed:
    build:
      context: ./seed/Application/
      dockerfile: Dockerfile
      target: debug
    volumes:
      - ./seed/:/seed/
    working_dir: /seed/
    ports:
      - "5000:5000"
    command: sh -c "dotnet restore Seed.sln && dotnet ef database update -p Infrastructure/Infrastructure.csproj && dotnet run -p Application/Application.csproj"
    # testar csharp no lugar de command