version: "3.4"
services:
  seed:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    volumes:
      - ./:/app/
    working_dir: /app
    command: sh -c  "dotnet build && dotnet ef database update --project Infrastructure --context SqlServerContext --verbose"
    container_name: seed
    depends_on:
      - db
  db:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 1Secure*Password1
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
